// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rjtdqekyhahuknravzth.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqdGRxZWt5aGFodWtucmF2enRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4ODE0ODcsImV4cCI6MjA0NjQ1NzQ4N30.wx9P299_mzSNgQVnSraACTmRW2JYaiahDedvbZEWI_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);